version: '3.8'

services:
  s_api:
    image: api_image
    container_name: c_api
    build:
      context: .
      dockerfile: src/Presentation/API/Dockerfile
    ports:
      - "5501:5501"
    networks:
      - test-internal
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:5501
      - ConsulConfig__Id=AppService
      - ConsulConfig__Name=AppService
      - ConsulConfig__ConsulAddress=http://s_consul:8500
      - ConsulConfig__Address=http://c_api_order:5501
      - TZ=Asia/Baku
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:5501/api/health || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

networks:
  test-internal:
    external: true